class AppStrings {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'hello': 'Hello',
      'appName': 'Aarogyan',
      'login': 'Login',
      'signup': 'Sign Up',
      'email': 'Email',
      'password': 'Password',
      'fullName': 'Full Name',
      'iAmDoctor': 'I am a Doctor',
      'alreadyHaveAccount': 'Already have an account? Log in',
      'dontHaveAccount': 'Don\'t have an account? Sign up',
      'invalidCredentials': 'Invalid credentials',
      'signUpSuccess': 'Registration successful!',
      'emotionalDiary': 'Emotional Diary',
      'recordYourFeelings': 'Record your feelings',
      'moodTracker': 'Mood Tracker',
      'trackYourProgress': 'Track your progress',
      'documents': 'Documents',
      'storeMedicalRecords': 'Store medical records',
      'aiAssistant': 'AI Assistant',
      'getGuidance': 'Get guidance',
      'diet': 'Diet',
      'getDietPlan': 'Get personalized diet plan',
      'fitness': 'Fitness',
      'getFitnessExercises': 'Get fitness exercises',
      'settings': 'Settings',
      'manageYourAccount': 'Manage your account',
      'language': 'Language',
      'selectLanguage': 'Select Language',
      'demographics': 'Demographics',
      'age': 'Age',
      'gender': 'Gender',
      'medicalConditions': 'Medical Conditions',
      'healthIssues': 'Health Issues',
      'save': 'Save',
      'cancel': 'Cancel',
      'howAreYouFeeling': 'How are you feeling today?',
      'yourNextAppointment': 'Your Next Appointment',
      'generalCheckup': 'General Checkup',
      'tomorrow': 'Tomorrow',
      'drSmith': 'Dr. Smith',
      'dietAgent': 'Diet Assistant',
      'dietDescription': 'Get personalized diet recommendations',
      'fitnessAgent': 'Fitness Coach',
      'fitnessDescription': 'Get customized exercise routines',
      'askDiet': 'Ask about diet...',
      'askFitness': 'Ask about fitness...',
      'logout': 'Logout',
      'profile': 'Profile',
      'help': 'Help',
      'typeYourMessage': 'Type your message...',
      'searchPatient': 'Search Patient',
      'patientID': 'Patient ID',
      'medicalHistory': 'Medical History',
      'consultationNotes': 'Consultation Notes',
      'memoNote': 'Memo Note',
      'recordNote': 'Record Note',
    },
    'hi': {
      'hello': 'नमस्ते',
      'appName': 'आरोग्य',
      'login': 'लॉगिन करें',
      'signup': 'साइन अप करें',
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'fullName': 'पूरा नाम',
      'iAmDoctor': 'मैं एक डॉक्टर हूं',
      'alreadyHaveAccount': 'पहले से खाता है? लॉगिन करें',
      'dontHaveAccount': 'खाता नहीं है? साइन अप करें',
      'invalidCredentials': 'अमान्य साक्षर पत्र',
      'signUpSuccess': 'पंजीकरण सफल!',
      'emotionalDiary': 'भावनात्मक डायरी',
      'recordYourFeelings': 'अपनी भावनाएं दर्ज करें',
      'moodTracker': 'मूड ट्रैकर',
      'trackYourProgress': 'अपनी प्रगति ट्रैक करें',
      'documents': 'दस्तावेज़',
      'storeMedicalRecords': 'चिकित्सा रिकॉर्ड संग्रहीत करें',
      'aiAssistant': 'एआई सहायक',
      'getGuidance': 'मार्गदर्शन प्राप्त करें',
      'diet': 'आहार',
      'getDietPlan': 'व्यक्तिगत आहार योजना प्राप्त करें',
      'fitness': 'फिटनेस',
      'getFitnessExercises': 'फिटनेस अभ्यास प्राप्त करें',
      'settings': 'सेटिंग्स',
      'manageYourAccount': 'अपना खाता प्रबंधित करें',
      'language': 'भाषा',
      'selectLanguage': 'भाषा चुनें',
      'demographics': 'जनसांख्यिकी',
      'age': 'आयु',
      'gender': 'लिंग',
      'medicalConditions': 'चिकित्सा स्थितियां',
      'healthIssues': 'स्वास्थ्य समस्याएं',
      'save': 'सहेजें',
      'cancel': 'रद्द करें',
      'howAreYouFeeling': 'आप आज कैसा महसूस कर रहे हैं?',
      'yourNextAppointment': 'आपकी अगली नियुक्ति',
      'generalCheckup': 'सामान्य जांच',
      'tomorrow': 'कल',
      'drSmith': 'डॉक्टर स्मिथ',
      'dietAgent': 'आहार सहायक',
      'dietDescription': 'व्यक्तिगत आहार सिफारिशें प्राप्त करें',
      'fitnessAgent': 'फिटनेस कोच',
      'fitnessDescription': 'अनुकूलित व्यायाम दिनचर्या प्राप्त करें',
      'askDiet': 'आहार के बारे में पूछें...',
      'askFitness': 'फिटनेस के बारे में पूछें...',
      'logout': 'लॉग आउट करें',
      'profile': 'प्रोफाइल',
      'help': 'मदद',
      'typeYourMessage': 'अपना संदेश दर्ज करें...',
      'searchPatient': 'रोगी खोजें',
      'patientID': 'रोगी आईडी',
      'medicalHistory': 'चिकित्सा इतिहास',
      'consultationNotes': 'परामर्श नोट्स',
      'memoNote': 'मेमो नोट',
      'recordNote': 'नोट रिकॉर्ड करें',
    },
    'mr': {
      'hello': 'नमस्कार',
      'appName': 'आरोग्य',
      'login': 'लॉगिन करा',
      'signup': 'साइन अप करा',
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'fullName': 'पूर्ण नाव',
      'iAmDoctor': 'मी एक डॉक्टर आहे',
      'alreadyHaveAccount': 'आधीच खाते आहे? लॉगिन करा',
      'dontHaveAccount': 'खाते नाहीत? साइन अप करा',
      'invalidCredentials': 'अमान्य क्रेडेंशियल्स',
      'signUpSuccess': 'नोंदणी यशस्वी!',
      'emotionalDiary': 'भावनिक डायरी',
      'recordYourFeelings': 'तुमच्या भावना नोंदवा',
      'moodTracker': 'मूड ट्रॅकर',
      'trackYourProgress': 'तुमची प्रगती ट्रॅक करा',
      'documents': 'दस्तऐवज',
      'storeMedicalRecords': 'वैद्यकीय नोंदी साठवा',
      'aiAssistant': 'एआই सहायक',
      'getGuidance': 'मार्गदर्शन मिळवा',
      'diet': 'आहार',
      'getDietPlan': 'व्यक्तिगत आहार योजना मिळवा',
      'fitness': 'फिटनेस',
      'getFitnessExercises': 'फिटनेस व्यायाम मिळवा',
      'settings': 'सेटिंग्ज',
      'manageYourAccount': 'तुमचे खाते व्यवस्थापित करा',
      'language': 'भाषा',
      'selectLanguage': 'भाषा निवडा',
      'demographics': 'जनसांख्यिकी',
      'age': 'वय',
      'gender': 'लिंग',
      'medicalConditions': 'वैद्यकीय स्थितीं',
      'healthIssues': 'आरोग्य समस्या',
      'save': 'साठवा',
      'cancel': 'रद्द करा',
      'howAreYouFeeling': 'तुम्ही आज कसा आहात?',
      'yourNextAppointment': 'तुमची पुढील भेट',
      'generalCheckup': 'सामान्य तपासणी',
      'tomorrow': 'उद्या',
      'drSmith': 'डॉ. स्मिथ',
      'dietAgent': 'आहार सहायक',
      'dietDescription': 'व्यक्तिगत आहार शिफारसी मिळवा',
      'fitnessAgent': 'फिटनेस कोच',
      'fitnessDescription': 'सुसंगत व्यायाम दिनचर्या मिळवा',
      'askDiet': 'आहारबद्दल विचारा...',
      'askFitness': 'फिटनेसबद्दल विचारा...',
      'logout': 'लॉग आउट करा',
      'profile': 'प्रोफाइल',
      'help': 'मदत',
      'typeYourMessage': 'तुमचा संदेश लिहा...',
      'searchPatient': 'रोगी शोधा',
      'patientID': 'रोगी आयडी',
      'medicalHistory': 'वैद्यकीय इतिहास',
      'consultationNotes': 'सल्लामसलत नोट्स',
      'memoNote': 'मेमो नोट',
      'recordNote': 'नोट रेकॉर्ड करा',
    },
  };

  static String get(String key, String languageCode) {
    return translations[languageCode]?[key] ?? translations['en']![key] ?? key;
  }
}
